"""empty message

Revision ID: 63c15efd1eba
Revises: 
Create Date: 2023-03-05 13:51:11.343225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63c15efd1eba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_news', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('dataset_day', schema=None) as batch_op:
        batch_op.alter_column('website_id',
               existing_type=mysql.INTEGER(display_width=5),
               comment=None,
               existing_comment='哪個網站',
               existing_nullable=False)
        batch_op.alter_column('table_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               comment=None,
               existing_comment='哪個排行榜',
               existing_nullable=False)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('buy_amount',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('buy_high',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('buy_low',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('buy_average',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('buy_average_yesterday',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('buy_change_percent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('sell_amount',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('sell_high',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('sell_low',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('sell_average',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('sell_average_yesterday',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('sell_change_percent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('text_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='文字自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('image_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='圖片自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('file_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='文件自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('last_message_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最後發送訊息時間',
               existing_nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('chatroom',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('text_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='文字自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('image_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='圖片自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('file_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='文件自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('join_member_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='加入會員時間',
               existing_nullable=True)
        batch_op.alter_column('last_message_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最後發送訊息時間',
               existing_nullable=True)
        batch_op.drop_index('user_id_UNIQUE')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_favorite_company', schema=None) as batch_op:
        batch_op.alter_column('company_ids',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment=None,
               existing_comment='使用者自選股，股票代號')
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index('userid_UNIQUE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_company', schema=None) as batch_op:
        batch_op.create_index('userid_UNIQUE', ['userid'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('company_ids',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='使用者自選股，股票代號')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.create_index('user_id_UNIQUE', ['user_id'], unique=False)
        batch_op.alter_column('last_message_time',
               existing_type=mysql.DATETIME(),
               comment='最後發送訊息時間',
               existing_nullable=True)
        batch_op.alter_column('join_member_time',
               existing_type=mysql.DATETIME(),
               comment='加入會員時間',
               existing_nullable=True)
        batch_op.alter_column('file_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='文件自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('image_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='圖片自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('text_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='文字自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=False)

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('chatroom',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('last_message_time',
               existing_type=mysql.DATETIME(),
               comment='最後發送訊息時間',
               existing_nullable=True)
        batch_op.alter_column('file_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='文件自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('image_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='圖片自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))
        batch_op.alter_column('text_reply',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='文字自動回覆開關',
               existing_nullable=False,
               existing_server_default=sa.text("'on'"))

    with op.batch_alter_table('dataset_day', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('sell_change_percent',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('sell_average_yesterday',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('sell_average',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('sell_low',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('sell_high',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('sell_amount',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('buy_change_percent',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('buy_average_yesterday',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('buy_average',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('buy_low',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('buy_high',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('buy_amount',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
        batch_op.alter_column('table_name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment='哪個排行榜',
               existing_nullable=False)
        batch_op.alter_column('website_id',
               existing_type=mysql.INTEGER(display_width=5),
               comment='哪個網站',
               existing_nullable=False)

    with op.batch_alter_table('company_news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
